shankarlohar/Hacktober-Fests

README.md
added YouTube embed on the README.md
=> readme tutorial update

README.md, index.html
=> webpage tutorial update

index.html, style.css
Hey buddy, hope you are doing well, please merge and accept my PR. Thankyou
=> Added My name card in index.html

index.html
Please check this out I have fixed the mentioned issue and please accept the pull request and merge this branch.
The issue no. is #22
=> Video Embedded Issue Fixed

README.md, index.html, style.css
all the steps have been followed and made the changes according to them. please review my pr.
=> Changes Made

login page/lp.css, login page/lp.html
@ShankarLohar , Hey i have attached the require folder
please merge this under hacktoberfest label it will be very helpful
thank you.
=> login page

index.html, style.css
Login button added and Updated the Navbar!
Please do merge and Add Hacktoberfest label.
Also, Please resolve the merge conflict.
=> Login button Added

index.html, style.css
#31 I animated the text "Learning git and  Github" to move left and right.
=> moved text Learning git and Github

index.html
Closes #67 
Initially I planned to something with z-index but it was not necessary as 'position-relative' did the job. I've also added a 'Team Member' card for myself
=> Made 'Login' button's position relative

README.md, index.html
Fixed the grid layout of the members' page.
Added Anirudh AV to the members' list.
Added Anirudh A V to the contributors' list.
=> Fixed the Grid & Added a member

README.md, index.html, style.css
=> Fixed Navbar Color, Background color : Added another section

README.md, index.html
=> Abhishek added Card

.vscode/settings.json, README.md, index.html, style.css
Contribution added in Readme file
=> Contributor

index.html
=>  Changes to be committed:

index.html
=> Updated HTML Files

README.md
I have just added my contribution part over this readme, and the other space changes were made by the default vs code formatter
=> Updated Contributions List

index.html, style.css
@shankarlohar I have added footer to your website which is responsive as well. Please merge my pull request. You can further edit the links to social media platforms as well as heading titles
=> Responsive-Footer

index.html, style.css
Reverts shankarlohar/Hacktober-Fests#145
=> Revert "fixed css"

README.md, index.html, style.css
Followed the README.md and implemented as instructed.
=> Instructions successfully implemented

.vscode/settings.json, index.html, main.js, style.css
Reverts shankarlohar/Hacktober-Fests#154
=> Revert "Editted cards UI" broken page

index.html
also on clicking the icon the user will redirect to another page of your profile.
=> Update index.html and added repo owner links to the footer symbols.

README.md, index.html, style.css
=> Ekraj Ghimire

index.html
@shankarlohar please accept my pr
=> added new card

index.html
I have modified the required colors @shankarlohar
=> modified-colors
